# Workflow to build the environment
name: ci
on: 
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout the repository on ubuntu runner
         uses: actions/checkout@v4
       - name: Install Java version 11
         uses: actions/setup-java@v4
         with:
           distribution: 'temurin' # See 'Supported distributions' for available options
           java-version: '11'
       - name: Build with Maven
         run: |
           mvn package
           ls -l
       - name: Upload Artifact
         uses: actions/upload-artifact@v4
         with:
           name: devops-war
           path: target/devops.war
     
  deploy:
    runs-on: gagan-devops
    environment: prod
    needs: build
    steps:
      - name: download the artifacts
        uses: actions/download-artifact@v4
        with:
          name: devops-war
          path: /tmp/
      - name: Deploy the app
        run: |
          sudo systemctl stop tomcat
          sudo cp /tmp/devops.war /opt/tomcat/webapps/
          sudo systemctl start tomcat
     
           
         
    
